chart: "kube-prometheus-stack"
repository: "https://prometheus-community.github.io/helm-charts"
version: "68.4.*"
namespace: "prometheus"

cleanPrometheusOperatorObjectNames: true

crds:
  enabled: true

prometheusOperator:
  enabled: true

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: false

defaultRules:
  create: false

kubelet:
  enabled: false

kubeApiServer:
  enabled: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

kubeScheduler:
  enabled: false
